[build]
  command = "serve -s build "
  publish = "build"
  functions = "functions"

# Указываем Netlify использовать кэш для ускорения сборки
[build.environment]
  NODE_MODULES_CACHE = "true"
  YARN_CACHE_FOLDER = ".yarn-cache"
