[build]
  publish = "build"
  command = "echo 'Skipping build step'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_MODULES_CACHE = "true"
  YARN_CACHE_FOLDER = ".yarn-cache"
